baseURL: "https://gotugboat.io/"
languageCode: "en-us"
title: "Tugboat"

theme: doks

# asdf workaround
# https://github.com/gohugoio/hugo/issues/9811
security:
  exec:
    osEnv:
      - '(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$'
      - ^ASDF_DIR$
      - ^HOME$
